variables:
  IMAGE_NAME: buffalo147/dev-apps
  IMAGE_TAG: portfolio-web-2ab5b5e5

stages:
  - build
  - deploy

  
build:
  stage: build
  image: quay.io/buildah/stable:latest
  # Rule: Don't run build if commit message says "[skip build]"
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip build\]/'
      when: never
    - when: on_success
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
  before_script:
    - buildah login -u "$REGISTRY_USER" -p "$REGISTRY_PASS" docker.io
  script:
    - |
      # Create manifest list
      buildah manifest create $IMAGE_NAME:$IMAGE_TAG
      
      # Build and add amd64
      buildah bud \
        --arch=amd64 \
        --timestamp 0 \
        --manifest $IMAGE_NAME:$IMAGE_TAG \
        -f docker/Dockerfile .
      
      # Build and add arm64
      buildah bud \
        --arch=arm64 \
        --timestamp 0 \
        --manifest $IMAGE_NAME:$IMAGE_TAG \
        -f docker/Dockerfile .
      
      # Push the manifest list
      buildah manifest push --all \
        $IMAGE_NAME:$IMAGE_TAG \
        docker://$IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  tags:
    - deploy
    - kls
  # Use a pre-built image with kubectl (Faster/Safer)
  image: 
    name: bitnami/kubectl:latest
    entrypoint: [""]
  variables:
    IMAGE: "$IMAGE_NAME:$IMAGE_TAG"
  script:
    - echo "$KUBE_CONFIG" | base64 -d > kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig
    
    # Create Registry Secret
    - kubectl create secret docker-registry docker-registry-secret
        --docker-server=docker.io
        --docker-username=$REGISTRY_USER
        --docker-password=$REGISTRY_PASS
        --dry-run=client -o yaml | kubectl apply -f -
        
    # Update Deployment image
    - sed -i "s|IMAGE_PLACEHOLDER|$IMAGE|g" k8s/deployment.yaml
    
    # Apply changes
    - kubectl apply -f k8s/