variables:
  IMAGE_NAME: buffalo147/dev-apps
  IMAGE_TAG: portfolio-web

stages:
  - build
  - deploy

  
build:
  stage: build
  image: quay.io/buildah/stable:latest
  variables:
    STORAGE_DRIVER: vfs
    BUILDAH_FORMAT: docker
  before_script:
    - buildah login -u "$REGISTRY_USER" -p "$REGISTRY_PASS" docker.io
  script:
    - |
      # Create manifest list
      buildah manifest create $IMAGE_NAME:$IMAGE_TAG
      
      # Build and add amd64
      buildah bud \
        --arch=amd64 \
        --timestamp 0 \
        --manifest $IMAGE_NAME:$IMAGE_TAG \
        -f docker/Dockerfile .
      
      # Build and add arm64
      buildah bud \
        --arch=arm64 \
        --timestamp 0 \
        --manifest $IMAGE_NAME:$IMAGE_TAG \
        -f docker/Dockerfile .
      
      # Push the manifest list
      buildah manifest push --all \
        $IMAGE_NAME:$IMAGE_TAG \
        docker://$IMAGE_NAME:$IMAGE_TAG

deploy:
  stage: deploy
  tags:
    - deploy
    - kls
  image:
    name: alpine:latest
    entrypoint: [""]
  variables:
    IMAGE: "$IMAGE_NAME:$IMAGE_TAG"
  before_script:
    - apk add --no-cache curl
    - 'KUBECTL_ARCH=$(uname -m | sed -e "s/^x86_64$/amd64/" -e "s/^aarch64$/arm64/" -e "s/^armv7l$/arm/") && [ -n "$KUBECTL_ARCH" ] || { echo "Unsupported architecture: $(uname -m)"; exit 1; }'
    - 'echo "Downloading kubectl for architecture: $KUBECTL_ARCH"'
    - 'curl -LO "https://dl.k8s.io/release/v1.32.0/bin/linux/${KUBECTL_ARCH}/kubectl"'
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/

  script:
    - echo "$KUBE_CONFIG" | base64 -d > kubeconfig
    - export KUBECONFIG=$PWD/kubeconfig
    - kubectl version
    - |
      kubectl create secret docker-registry docker-registry-secret \
        --docker-server=docker.io \
        --docker-username=$REGISTRY_USER \
        --docker-password=$REGISTRY_PASS \
        --dry-run=client -o yaml | kubectl apply -f -
    - sed -i "s|IMAGE_PLACEHOLDER|$IMAGE|g" k8s/deployment.yaml
    - kubectl apply -f k8s/